<?php
/**
 * Created by PhpStorm.
 * User: yifeng
 * Date: 2017/12/16
 * Time: 23:41
 */

namespace app\index\controller;


use think\Controller;

class Common extends Controller
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $cate=$this->getcate();
        //获取当前所访问一级栏目标识
        $currcontroller=request()->controller();
        $currtype=$this->getcurrtype($currcontroller);
        //获取网站配置信息
        $config=db('config')->field('config')->find();
        //解码配置信息
        $config=json_decode($config['config'],true);
        //判读网站状态
        if(!isset($config['state'])){
            $config['state']=0;
        }
        $this->checkweb($config['state'],$config['closeinfo']);
        $this->assign([
            'cate'=>$cate,
            'currtype'=>$currtype,
            'config'=>$config
        ]);
    }

    /**
     * 获取导航栏目
     * @return false|\PDOStatement|string|\think\Collection
     */
    private function getcate(){
        $res=db('category')->where('pid',0)->where('isshow',1)->order('sort desc,id Asc')->field('id,name,type')->select();
        foreach ($res as $k=>$v){
            $res_child=db('category')->where('pid',$v['id'])->where('isshow',1)->order('sort desc,id Asc')->field('id,name,type')->select();
            $res[$k]['child']=$res_child;
        }
        return $res;
    }

    private function getcurrtype($controller){
        switch ($controller){
            case 'Index':
                return 0;
            case 'Page':
                return 1;
            case 'Works':
                return 2;
            case 'Model':
                return 3;
            case 'Scene':
                return 4;
            case 'News':
                return 5;
            case 'Contactus':
                return 7;
            default:
                return 0;
        }
    }
    private function checkweb($state,$info="网站已关闭"){
        if($state!=1){
            header('Content-Type:text/html;charset=utf-8');
            echo $info;
            exit;
        }
    }
    //左侧子栏目列表
    protected function getchild($mark='about'){
        $res_pid=db('category')->where('mark',$mark)->field('id')->find();
        $res=db('category')->where('pid',$res_pid['id'])->field('id,name,type')->select();
        return $res;
    }
    //获取当前位置
    //首页>关于我们>公司简介
    /**
     * @param $id 最小级别的栏目Id,根据这个id获取到它的所有上级分类
     */
//    protected function getlocation($id){
//        $cate=db('category')->where('id',$id)->field('id,name,pid')->find();
//        $arr=[];
//        if($cate){
//            $arr[]=$cate['name'];
//            if($cate['pid']!=0){
//                $pre_cate=$this->getlocation($cate['pid']);
//                $arr=array_merge($pre_cate,$arr);
//            }
//            return $arr;
//        }
//    }
}