<?php
/**
 * Created by PhpStorm.
 * User: yifeng
 * Date: 2017/12/17
 * Time: 0:21
 */

namespace app\index\controller;


class Page extends Common
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        //返回左侧栏目列表
        $about=$this->getchild('about');
        $zuopin=$this->getchild('zuopin');
        $this->assign([
            'about'=>$about,
            'zuopin'=>$zuopin
        ]);
    }

    public function index($id){
        //获取单页内容
        $page=db('category')->where('id',$id)->find();
        if(!$page){
            //$this->error("访问数据不存在");
            //手动抛出异常
            abort(404);
        }
        $this->assign('page',$page);
        //当前栏目ID
        $this->assign('currid',$id);
        return view();
    }

    //专业团队
    public function team(){
        $id=db('category')->where('mark','team')->field('id')->find();
        $this->assign('currid',$id['id']);
        $team=db('article')->alias('a')
            ->join('pics b','b.aid=a.id')
            ->where('a.cid',$id['id'])->field('a.id,a.title,a.zhiwu,a.zhicheng,b.pic')
            ->paginate(1);
        $this->assign('team',$team);
        return view();
    }

    //专业团队详情页
    public function teamshow($id){

        //获取团详情
        $res=db('article')->where('id',$id)->field('cid,title,keyword,desc,content')->find();
        //当前位置的获取的获取
//        $curlocation=$this->getlocation($res['cid']);
//        $this->assign('curlocation',$curlocation);
        $this->assign('currid',$res['cid']);
        $this->assign('team',$res);
        return view();
    }
}